### ISSUE TITLE
Headers matching fails due to splitting multi-value values

### ISSUE THREAD

**Issue by artemptushkin** [pact-foundation/pact-jvm#1398]
I migrate from `au.com.dius.pact.provider:junit:4.1.11` to `4.2.7`, same issue with `4.1.23`

Some tests started failing on:
```
1) Get current account billing information status value includes headers "access-control-allow-headers" with value "[Content-Type, Authorization]"

    1.1) header: Expected header 'access-control-allow-headers' to have value 'Content-Type, Authorization' but was 'Content-Type'
    
    1.2) header: Expected header 'access-control-allow-methods' to have value 'POST, GET, PUT, HEAD, DELETE, OPTIONS, PATCH' but was 'POST'

    1.3) header: Expected header content-type to have value 'application/json, charset=utf-8' but was 'application/json;charset=utf-8'
```

Pact looks like this:

```json
"response": {
                "status": 200,
                "headers": {
                    "access-control-allow-credentials": "true",
                    "access-control-allow-headers": "Content-Type, Authorization",
                    "access-control-allow-methods": "POST, GET, PUT, HEAD, DELETE, OPTIONS, PATCH",
                    "content-type": "application/json, charset=utf-8"
                }
            }
```

The provider response headers looks like this:

```
'Access-Control-Allow-Headers': 'Content-Type, Authorization'
'Access-Control-Allow-Methods': 'POST, GET, PUT, HEAD, DELETE, OPTIONS, PATCH'
```

Obviously, headers are identical, should match. Case sensitive difference it has only, but it isn't the problem as I see in debug: it reaches [this line](https://github.com/pact-foundation/pact-jvm/blob/ea08a38ac969d2a6526a7b47564956aa45840cde/core/matchers/src/main/kotlin/au/com/dius/pact/core/matchers/Matching.kt#L134)

Looks like it splits the actual response headers and then fails to match. Is this something expected?

**Comment by uglyog** [comment]
What has generated your Pact file? Are you able to provide the complete file?

**Comment by artemptushkin** [comment]
@uglyog like this:

```yaml
"response": {
                "status": 200,
                "headers": {
                    "access-control-allow-credentials": "true",
                    "access-control-allow-headers": "Content-Type, Authorization",
                    "access-control-allow-methods": "POST, GET, PUT, HEAD, DELETE, OPTIONS, PATCH",
                    "content-type": "application/json, charset=utf-8"
                }
            }
```
