### ISSUE TITLE
Use static port in consumer mockserver, or use dynamic port in application

### ISSUE THREAD

**Issue by kevindeboer** [pact-foundation/pact-jvm#1638]
Hi, 

I am currently learning the pact framework by rewriting some of our wiremock tests. (I know there is a community wiremock plugin, but i'd also like to try my hand with learning the actual pact framework). 

It feels like I am missing something obvious, but after a whole day of googling and reading docs, I cant seem to find a way to configure my application to use the pact mockserver instead of wiremock. 

Currently in my application.yaml i'd have something like:

```
application:
  client:
      otherservice:
        url: http://localhost:4242/
```

In which I have set wiremock to run on a static 4242 port. All outgoing calls from the consuming service to 'otherservice' would be routed to wiremock instead.

I could also let wiremock decide on a random port, which I can use in my application.yaml like:

```
application:
  client:
      service:
        url: http://localhost:${wiremock.server.port}/
```

However, with pact, I cant seem to find a way to either start the mockserver with a static port, or use whatever port is chosen in my application yaml. I checked the system properties https://docs.pact.io/implementation_guides/jvm/docs/system-properties, and none seem to either expose the chosen port, or allow the option to set one myself. I also checked the source code and found the MockProviderConfig class which holds the port. However I am both unfamiliar with Kotlin, and also couldn't find any examples of starting the mockserver with custom config.

Am I trying something fundamentally wrong here?
